### ISSUE TITLE
参考LabelPlus的Issues进行改进

### ISSUE THREAD

**Issue by Meodinger** [Meodinger/LabelPlusFX#7]
年后发布v2.2.2，这个版本算是穷尽了我能想到的东西，准备参看LabelPlus的Issues继续进行改进

**Comment by Meodinger** [comment]
- [x] 插入标号 LabelPlus/LabelPlus#10
 - [x] 保存进度 LabelPlus/LabelPlus#40
 - [x] 简繁转换 LabelPlus/LabelPlus#58
 - [x] 窗口大小 LabelPlus/LabelPlus#69
 - [x] 框选选中 LabelPlus/LabelPlus#70
 - [x] 拖拽打开 LabelPlus/LabelPlus#72
 - [x] 移动标号 LabelPlus/LabelPlus#73
 - [x] 立即翻译 LabelPlus/LabelPlus#78
 - [x] 文件信息 LabelPlus/LabelPlus#86
 - [x] 错误检查 LabelPlus/LabelPlus#88
 - [x] 保存目录 LabelPlus/LabelPlus#96
 - [x] 路径分离 LabelPlus/LabelPlus#97
